package QuizPackage;


import javax.swing.ImageIcon;
import javax.swing.JRadioButton;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author malil6384
 */
public class Quiz extends javax.swing.JFrame {

    /**
     * Creates new form Quiz
     */
    public Quiz() {
        initComponents();
        //Runs the question main method when the program starts
        //To begin the question number counting
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionGroup = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblQuestion1 = new javax.swing.JLabel();
        iconQuestionImage = new javax.swing.JLabel();
        rdoA1 = new javax.swing.JRadioButton();
        rdoA2 = new javax.swing.JRadioButton();
        rdoA3 = new javax.swing.JRadioButton();
        rdoA4 = new javax.swing.JRadioButton();
        btnAnswerSubmit = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 255));
        lblTitle.setText("Video Game Quiz!!");

        lblQuestion1.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        lblQuestion1.setForeground(new java.awt.Color(0, 0, 255));
        lblQuestion1.setText("What game is this?");

        iconQuestionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizPackage/halo2A2.jpg"))); // NOI18N

        questionGroup.add(rdoA1);
        rdoA1.setText("Call of Duty");
        rdoA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoA1ActionPerformed(evt);
            }
        });

        questionGroup.add(rdoA2);
        rdoA2.setText("Borderlands");
        rdoA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoA2ActionPerformed(evt);
            }
        });

        questionGroup.add(rdoA3);
        rdoA3.setText("Halo 2A");

        questionGroup.add(rdoA4);
        rdoA4.setText("GTA V");

        btnAnswerSubmit.setText("Submit Answer");
        btnAnswerSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnswerSubmitActionPerformed(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("Comic Sans MS", 3, 12)); // NOI18N
        lblResult.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuestion1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iconQuestionImage)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rdoA2)
                                .addComponent(rdoA3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rdoA1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(rdoA4)
                            .addComponent(btnAnswerSubmit)
                            .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(44, 44, 44)
                .addComponent(lblQuestion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconQuestionImage)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdoA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoA2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoA3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdoA4)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnswerSubmit)))
                .addGap(18, 18, 18)
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoA1ActionPerformed

    }//GEN-LAST:event_rdoA1ActionPerformed

    private void rdoA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoA2ActionPerformed

    }//GEN-LAST:event_rdoA2ActionPerformed

    private void btnAnswerSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnswerSubmitActionPerformed
        //Run the main quiz method
        quizMainMethod();
        percentageCalculation();
    }//GEN-LAST:event_btnAnswerSubmitActionPerformed
    
    //General variable declaration
    public double score = 0;
    public double percent;
    public int questionNumber = 1;
    
    //Array containing images that can be pulled
    public ImageIcon[] imageArray = {
        new ImageIcon(getClass().getResource("/QuizPackage/halo2A.jpg")),
        new ImageIcon(getClass().getResource("/QuizPackage/minecraft.jpg")),
        new ImageIcon(getClass().getResource("/QuizPackage/darksouls.jpg")),
        new ImageIcon(getClass().getResource("/QuizPackage/freddy.jpg")), 
        new ImageIcon(getClass().getResource("/QuizPackage/fortnite.jpg"))
    };
    
    
    //Two dimensional array that contain the question answers
    public String[][] questionAnswers = {
        {"Call of Duty", "Borderlands", "Halo 2A", "GTA V"}, 
        {"Minecraft", "Fortnite", "Roblox", "GTA V"},
        {"Fortntie", "Fall Guys", "Halo 2A", "Darksouls"},
        {"Roblox", "Borderlands", "Five Night's At Freddy's", "Minecraft"},
        {"Borderlands", "Fortnite", "Halo 2A", "GTA V"}
    };
    
    //Method that runs the quiz
    public void quizMainMethod(){
        //Switch case deciding which question image and options to display
        switch (questionNumber) {
            case 1:
                questionMethod(rdoA3);
                break;
            case 2:
                questionMethod(rdoA1);
                break;
            case 3:
                questionMethod(rdoA4);
                break;
            case 4:
                questionMethod(rdoA3);
                break;
            case 5:
                questionMethod(rdoA2);
                break;
            default:
                break;
        }
        //When the quiz is done, your mark will display on the screen
        
        
    }
    
    
    //Sub methods for each question
    public void questionMethod(JRadioButton rdo){
        //Run the image selection method
        imageDecision();
        //Run the question selection method
        questionAnswerDecision();
        //If the correct button is selected, it will count as a correct answer
        if(rdo.isSelected()){
            score++;
            questionNumber++;
        } else{
            //If any other button is selected, 
            //only the question number will increase
            questionNumber++;
        }
        
    }
   
    
    //Image deciding method
    public void imageDecision(){
        //Checks the question number value and changes the image based
        //on the number
        switch (questionNumber) {
            case 0:
                iconQuestionImage.setIcon(imageArray[0]);
                break;
            case 1:
                iconQuestionImage.setIcon(imageArray[1]);
                break;
            case 2:
                iconQuestionImage.setIcon(imageArray[2]);
                break;
            case 3:
                iconQuestionImage.setIcon(imageArray[3]);
                break;
            case 4:
                iconQuestionImage.setIcon(imageArray[4]);
                break;
            default:
                break;
        }
    }
    
    //Question decidiing method
    public void questionAnswerDecision(){
        //Checks the question number and sets the text of the answers
        //based on the question
        switch (questionNumber) {
            case 0:
                rdoA1.setText(questionAnswers[0][0]);
                rdoA2.setText(questionAnswers[0][1]);
                rdoA3.setText(questionAnswers[0][2]);
                rdoA4.setText(questionAnswers[0][3]);
                break;
            case 1:
                rdoA1.setText(questionAnswers[1][0]);
                rdoA2.setText(questionAnswers[1][1]);
                rdoA3.setText(questionAnswers[1][2]);
                rdoA4.setText(questionAnswers[1][3]);
                break;
            case 2:
                rdoA1.setText(questionAnswers[2][0]);
                rdoA2.setText(questionAnswers[2][1]);
                rdoA3.setText(questionAnswers[2][2]);
                rdoA4.setText(questionAnswers[2][3]);
                break;
            case 3:
                rdoA1.setText(questionAnswers[3][0]);
                rdoA2.setText(questionAnswers[3][1]);
                rdoA3.setText(questionAnswers[3][2]);
                rdoA4.setText(questionAnswers[3][3]);
                break;
            case 4:
                rdoA1.setText(questionAnswers[4][0]);
                rdoA2.setText(questionAnswers[4][1]);
                rdoA3.setText(questionAnswers[4][2]);
                rdoA4.setText(questionAnswers[4][3]);
                break;
            default:
                break;
        }
    }
    
    public void percentageCalculation(){
        //This if else statement makes sure the program doesn't try to divide 0
        //by anything, because it would result in an error.
        if(questionNumber >= 6){
            //This calculates the percentage
            percent = ((score / 5) * 100);
            System.out.println("" + percent);
            lblResult.setText("You Scored: " + score + "/5!" + "\n" + " This means you had a " + percent + "%!");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnswerSubmit;
    private javax.swing.JLabel iconQuestionImage;
    private javax.swing.JLabel lblQuestion1;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTitle;
    private javax.swing.ButtonGroup questionGroup;
    private javax.swing.JRadioButton rdoA1;
    private javax.swing.JRadioButton rdoA2;
    private javax.swing.JRadioButton rdoA3;
    private javax.swing.JRadioButton rdoA4;
    // End of variables declaration//GEN-END:variables
}
